cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('eshop.urls', namespace='eshop')),
    path('seller/', include('seller.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

eshop/urls.py
from django.urls import path
from . import views

app_name = 'eshop'

urlpatterns = [
    path('',views.product_list, name='product_list'),
    path('all_product/',views.all_product, name='all_product'),
    #path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<slug:category_slug>/', views.all_product, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
    ]

orders/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/',views.order_create, name='order_create'),
]

orders/models.py
from django.db import models
from eshop.models import Product

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

orders/views.py
from django.shortcuts import render
from .models import  OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])

            #clear the cart
            cart.clear()
            return render(request,'created.html',{'order':order})
    else:
        form = OrderCreateForm()
    return render(request,'create.html',{'cart':cart, 'form':form})

orders/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet" />
    <!-- Font-Awesome CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    <!-- Google Font Family CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/base.css' %}" />
    <title>{% block title %}Ecommerce Project{% endblock %}</title>

</head>

<body>


<header>


    <nav class="navbar navbar-expand-lg navbar-light bg-light topnavbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'eshop:product_list' %}" id="BrandName">Ecommerce Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'eshop:product_list' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link shipping" href="#">Shipping Policy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Return Policy</a>
                    </li>

                            {% with total_items=cart|length %}
                            {% if total_items > 0 %}
                            <li class="nav-item" >
                                <a class="nav-link" href="{% url 'cart:cart_detail' %}"  >
                                    <i class="fa fa-shopping-cart cart "data-toggle="tooltip" data-placement="bottom"
                                       data-original-title="Tooltip on bottom"
                                       class="red-tooltip" title="{{ total_items }} item{{ total_items|pluralize }},${{ cart.get_total_price }}"  aria-hidden="true"></i>
                                </a>
                            </li>
                            {% else %}
                            <li class="nav-item" >
                                <a class="nav-link" href="#"  >
                                    <i class="fa fa-shopping-cart cart "data-toggle="tooltip" data-placement="bottom"
                                       data-original-title="Tooltip on bottom"
                                       class="red-tooltip" title="No Product in the Cart"  aria-hidden="true"></i>
                                </a>
                            </li>
                            {% endif %}
                            {% endwith %}



                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="fa fa-user user" aria-hidden="true"></i>
                                </a>
                            </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

    




    <div id="content">
        {% block content %} {% endblock %}
    </div>


    <section class="footer">
        <div class="container py-4">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 mb-4">
                    <h6 class="text-uppercase">customer care</h6>
                    <div class="is-divider small" style="
                      background-color: rgba(255, 255, 255, 0.3) !important;
                    "></div>
                    <p class="text-uppercase">faq</p>
                    <hr style="border-color: rgba(255, 255, 255, 0.08)" />
                    <p>Return Policy</p>
                    <hr style="border-color: rgba(255, 255, 255, 0.08)" />
                    <p>Shipping Policy</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 mb-4">
                    <h6 class="text-uppercase">company info</h6>
                    <div class="is-divider small" style="
                      background-color: rgba(255, 255, 255, 0.3) !important;
                    "></div>
                    <p>About Us</p>
                    <hr style="border-color: rgba(255, 255, 255, 0.08)" />
                    <p>Privacy Policy</p>
                    <hr style="border-color: rgba(255, 255, 255, 0.08)" />
                    <p>Terms of Use</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <h6 class="text-uppercase">keep in touch</h6>
                    <div class="is-divider small" style="
                      background-color: rgba(255, 255, 255, 0.3) !important;
                    "></div>
                    <p>support@Ecommrce muntasir690000@gmail.com</p>
                    <hr style="border-color: rgba(255, 255, 255, 0.08)" />
                    <p>Contact Us</p>
                </div>
            </div>
        </div>
    </section>

    <footer style="background-color: #000000">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mt-3 mb-4">
                    <p style="color: #fff">
                        Copyright 2021 © muntasir690000@gmail.com
                    </p>
                </div>
                <div class="col-md-6 mt-3 mb-6">
                    <i class="fa fa-3x fa-cc-visa" aria-hidden="true"></i>
                    <i class="fa fa-3x fa-cc-paypal" aria-hidden="true"></i>
                    <i class="fa fa-3x fa-cc-mastercard" aria-hidden="true"></i>
                </div>
            </div>
        </div>
    </footer>

    <button onclick="topFunction()" id="myBtn" title="Go to top">
        <i class="fa fa-chevron-up" aria-hidden="true"></i>
    </button>

    <!--footer part end-->
    </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

    <script>
        $(window).on('load', function() { // makes sure the whole site is loaded
            $('#status').fadeOut(); // will first fade out the loading animation
            $('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
            $('body').delay(350).css({
                'overflow': 'visible'
            });
        })

        if ($(window).width() > 992) {
            $(window).scroll(function() {
                if ($(this).scrollTop() > 40) {
                    $('#navbar_top').addClass("fixed-top");
                    // add padding top to show content behind navbar
                    $('body').css('padding-top', $('.navbar').outerHeight() + 'px');
                } else {
                    $('#navbar_top').removeClass("fixed-top");
                    // remove padding top from body
                    $('body').css('padding-top', '0');
                }
            });
        } // end if
    </script>


</body>

</html>

orders/templates/create.html
{% extends "base.html" %} {% block title %} Checkout {% endblock %} {% block content %}
<h1>Checkout</h1>
<div class="order-info">
    <h3>Your order</h3>
    <ul>
        {% for item in cart %}
        <li>
            {{ item.quantity }}x {{ item.product.name }}
            <span>${{ item.total_price }}</span>
        </li>
        {% endfor %}
    </ul>
    <p>Total: ${{ cart.get_total_price }}</p>
</div>
<form method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
</form>
{% endblock %}

orders/templates/created.html
{% extends "base.html" %} {% block title %} Thank you {% endblock %} {% block content %}
<h1>Thank you</h1>
<p>Your order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</p>
{% endblock %}